name: Kotlin Lint Test

on:
  push:
    paths:
      - '**/*.kt'
      - '**/*.kts'
  pull_request:
    paths:
      - '**/*.kt'
      - '**/*.kts'

jobs:
  ktlint-lint:
    name: Run ktlintCheck
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'
          cache: gradle

      - name: Run ktlint (lint test)
        run: cd sdks/android && ./gradlew ktfmtCheck --quiet